#!/bin/bash
# Script to load the kernel module for the bme280
# and start the readout-script

start() {
	insmod /lib/modules/`uname -r`/extra/aesd_bme280.ko.xz
	python3 /aesd/read.py &
}

stop() {
	pkill python3
	rmmod aesd_bme280
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    *)
       echo "Usage: $0 {start|stop}"
esac

exit 0
